---
# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        exclude_types: [markdown, yaml]
        types: [jsx, ts, tsx, gitignore, json, css, javascript]
        args: ["--config", ".prettierrc", "--ignore-path", ".prettierignore"]
